import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import React from 'react';



const inter = Inter({ subsets: ["latin"] });

import LayoutContainer from '@/components/LayoutContainer';
import { ActivePageProvider } from '../context/ActivePageContext';

//import BootstrapClient from '@/components/BootstrapClient';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <ActivePageProvider>
    <html lang="en">
      <body className={inter.className}>
      <LayoutContainer>
          {children}
        </LayoutContainer>
      </body>
    </html>
    </ActivePageProvider>
    </>
  );
}
